connector:
  max_delta_time_hours: '168'

source:
  endpoint: 'https://opendata.aemet.es/opendata/'

sink:
  project_id: data-altostratus-challenge
  dataset_id: 'aemet_weather_data'
  table_name: 'weather_raw_data'
  location: 'EU'
  timestamp_column: 'fecha'
  first_date_to_load: '2023-06-3'

